name: Build Eloquence Add-on

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up 64-bit Python 3.13
        id: py64
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          architecture: x64

      - name: Set up 32-bit Python 3.13
        id: py32
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          architecture: x86
          update-environment: false

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Check locked dependencies
        run: uv lock --check

      - name: Lint
        run: runlint.bat
        shell: cmd

      - name: Install MSYS2 / gettext
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          install: gettext
          update: true

      - name: Add MSYS2 to PATH
        run: '"${{ steps.msys2.outputs.msys2-location }}\usr\bin" >> $env:GITHUB_PATH'
        shell: pwsh

      - name: Build 32-bit host
        run: build_host.cmd
        shell: cmd
        env:
          PYTHON32: ${{ steps.py32.outputs.python-path }}

      - name: Fetch proprietary files
        run: python fetch_eci.py

      - name: Build addon
        run: scons.bat && scons.bat pot
        shell: cmd

      - name: Upload add-on artifact
        uses: actions/upload-artifact@v7
        with:
          name: nvda-addon
          path: "*.nvda-addon"
          archive: false

      - name: Upload pot artifact
        uses: actions/upload-artifact@v7
        with:
          name: pot-file
          path: "*.pot"
          archive: false

      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.nvda-addon
            *.pot
